# 配置主菜单和社交菜单
#[[main]]
#identifier = "home"  # 菜单项标识符
#name = "Home"        # 菜单项名称
#url = "/"            # 菜单项链接
#[main.params]
#icon = "home"        # 菜单项图标
#newtab = true         # 是否在新标签页打开

[[social]]
identifier = "github"  # 社交菜单项标识符
name = "GitHub"        # 社交菜单项名称
url = "https://github.com/inkcoo/hugo-theme-stack-zh-cn"  # 社交菜单项链接

[social.params]
icon = "brand-github"  # 社交菜单项图标

[[social]]
identifier = "email"  # 社交菜单项标识符
name = "Email"        # 社交菜单项名称
url = "mailto:example@example.com"  # 社交菜单项链接

[social.params]
icon = "mail"  # 社交菜单项图标
